#!/usr/bin/env perl
use strict;
use utf8;
use Net::IPMessenger::Bot;
use Sys::Hostname ();

my $bot = Net::IPMessenger::Bot->new(
    configure => {
        NickName  => 'ipmsg_bot',
        GroupName => 'bot',
        UserName  => __PACKAGE__,
        HostName  => Sys::Hostname::hostname(),
    },
    # on_message => sub {
        # my $user = shift;
        # "Hello " . $user->nickname;
    # },
    on_message => [
        qr/hello/ => sub {
            my $user = shift;
            "Hello " . $user->nickname;
        },
        qr/goodbye/ => sub {
            my $user = shift;
            "Goodbye " . $user->nickname;
        },
    ],
);

$bot->start;
